Fix validation layer error VkBufferImageCopy-bufferOffset
Error: The bufferOffset must be a multiple of 4.
On NVIDIA cards the optimalBufferCopyOffsetAlignment value is 1,
therefore the alignment mask wasn't good in some cases.
https://www.vulkan.gpuinfo.org/displayreport.php?id=6217#limits